# Generated by Django 5.2.6 on 2025-09-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('None', 'None')], max_length=5)),
                ('energy', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.PositiveIntegerField()),
                ('times', models.PositiveIntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pets.dailylog')),
            ],
        ),
    ]
