# Generated by Django 5.2.6 on 2025-09-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_dailylog_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='times',
            new_name='times_per_day',
        ),
    ]
