# Generated by Django 5.2.6 on 2025-09-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_times_medication_times_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='surgery_reason',
            new_name='surgeryReason',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='surgery_type',
            new_name='surgeryType',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='times_per_day',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='medication',
            name='times',
            field=models.PositiveIntegerField(default=1, help_text='Times per day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='food',
            field=models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('None', 'None')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.PositiveIntegerField(help_text='Dosage in mg'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='pets.dailylog'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(),
        ),
    ]
