# Generated by Django 5.2.6 on 2025-09-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_surgery_reason_pet_surgeryreason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='surgeryReason',
            new_name='surgery_reason',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='surgeryType',
            new_name='surgery_type',
        ),
    ]
