# Generated by Django 5.0.4 on 2025-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_surgeryreason_pet_surgery_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
