# Generated by Django 5.0.4 on 2025-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_vetinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetinfo',
            name='clinic_name',
            field=models.CharField(max_length=80),
        ),
    ]
